# Generated by Django 2.2.2 on 2019-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('ssubject', models.CharField(max_length=40)),
                ('smarks', models.CharField(max_length=20)),
            ],
        ),
    ]
