# Generated by Django 2.2.2 on 2019-07-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=30)),
                ('nameprefix', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25)),
                ('fathername', models.CharField(max_length=30)),
                ('mothername', models.CharField(max_length=30)),
                ('mothermidname', models.CharField(max_length=35)),
                ('dob', models.CharField(max_length=30)),
                ('timeofbirth', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('doj', models.CharField(max_length=50)),
                ('qoj', models.CharField(max_length=25)),
                ('hoj', models.CharField(max_length=30)),
                ('yoj', models.CharField(max_length=25)),
                ('moj', models.CharField(max_length=25)),
                ('mnamej', models.CharField(max_length=20)),
                ('sm', models.CharField(max_length=30)),
                ('dayoj', models.CharField(max_length=40)),
                ('dowofj', models.CharField(max_length=30)),
                ('shortdow', models.CharField(max_length=20)),
                ('ageinc', models.CharField(max_length=25)),
                ('sal', models.CharField(max_length=30)),
                ('lhike', models.CharField(max_length=25)),
                ('ssn', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=25)),
                ('placename', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipp', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
