# Generated by Django 2.2.2 on 2019-06-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
